language: elixir
elixir:
  - 1.3.4
otp_release:
  - 18.1
sudo: false
env:
  - ELIXIR_ERL_OPTIONS=""
  - ELIXIR_ERL_OPTIONS="+T 9"
script:
  - mix test
notifications:
  recipients:
    - rcddeveloper@icloud.com
